# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Business-OnlinePayment-Multiplex
version:      0.01
version_from: lib/Business/OnlinePayment/Multiplex.pm
installdirs:  site
requires:
    Business::OnlinePayment:       
    Business::OnlinePayment::StoredTransaction: 
    Test::More:                    

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
